version: "3.3"

services:
  cfn_nag_cdk:
    image: "stelligent/cfn_nag"
    volumes:
      - ./cdk.out:/templates
    entrypoint: "find /templates -name '*.template.json' -maxdepth 1 -type f -exec cfn_nag --debug --no-allow-suppression  {} +"

  cfn_nag_cfn:
    image: "stelligent/cfn_nag"
    volumes:
      - ./prerequisites:/templates
    entrypoint: "find /templates -name '.yaml' -maxdepth 1 -type f -exec cfn_nag --debug --no-allow-suppression  {} +"
